// Generated by CoffeeScript 1.9.3

/**
 * fis.baidu.com
 */

(function() {
  var assert, crypto, exec, path;

  assert = require('assert');

  path = require('path');

  exec = require('child_process').execSync;

  crypto = require('crypto');

  module.exports = function(options) {
    var cmd, commands, dir, local_zipfile, remove_local_zip, scp_cmd, server, source, tmpFilename, to, unzip_cmd;
    assert(options.to, 'options.to is required!');
    assert(options.source, 'options.source is required!');
    to = options.to;
    source = options.source;
    server = options.server;
    dir = path.join(process.cwd(), source);
    tmpFilename = (crypto.randomBytes(36).toString('hex')) + ".zip";
    local_zipfile = path.join(source, tmpFilename);
    cmd = "cd " + dir + "; zip -r " + tmpFilename + " ./*";
    scp_cmd = "scp " + local_zipfile + " server:" + opt.to;
    unzip_cmd = "ssh " + server + " 'cd " + to + "; unzip -o " + tmpFilename + "; rm " + tmpFilename + "; exit'";
    remove_local_zip = "rm " + tmpFilename;
    return commands = [[cmd, '|||-> 本地打包完成'], [scp_cmd, '|||-> 上传完成'], [unzip_cmd, '|||-> 远程部署完成'], [a, remove_local_zip, '|||-> 本地清理完成']];
  };

  commands.each(function(e) {
    exec(e[0]);
    return console.log(e[1]);
  });

}).call(this);
